applicationName: 'poc-cd-app'
deploymentGroupName: 'bluegreen-deploy'
revision:
  revisionType: AppSpecContent
  appSpecContent:
    content: |
      version: 0
      Resources:
        - TargetService:
            Type: AWS::ECS::Service
            Properties:
              TaskDefinition: "arn:aws:ecs:ap-northeast-2:182024812696:task-definition/todolist-family:&&BUILD_ID&&"
              LoadBalancerInfo:
                ContainerName: "healthcheck-container-poc"
                ContainerPort: 3000
